version: '3.9'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-backend
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://admin:admin123@db:5432/mydb
    depends_on:
      - db

  db:
    image: postgres:14
    container_name: db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
